server:
  port: 8080
  context-path: /api-documentation

logging:
  level:
    org.anotherdev.sample: DEBUG

spring:
  thymeleaf:
    cache: false

org:
    anotherdev:
        documentation:
            api:
                petstore:
                    key: Swagger Petstore
                    value: https://raw.githubusercontent.com/swagger-api/swagger-editor/master/spec-files/petstore_full.yaml
                    role: ROLE_PETSTORE
                instagram:
                    key: Instagram API
                    value: https://raw.githubusercontent.com/swagger-api/swagger-editor/master/spec-files/instagram.yaml
                    role: ROLE_INSTAGRAM
                uber:
                    key: Uber API
                    value: https://raw.githubusercontent.com/swagger-api/swagger-editor/master/spec-files/default.yaml
                    role: ROLE_UBER
            users:
                super-user:
                    # BCryptPasswordEncoder encripted password: 123456
                    password: $2a$10$J8w8baz4VKmc5kO.MuWtXuUcR0iNdrIT3UfjZq7jou8g4Kq03WxrK
                    roles: ROLE_ADMIN,ROLE_INSTAGRAM,ROLE_UBER,ROLE_PETSTORE
                user1:
                    # BCryptPasswordEncoder encripted password: azertyuiop
                    password: $2a$10$IONw4cy/7AXIbbf/WGM0I.zrpmDRfHA9eBHVy3l7Oc8O/UP2jcLUG
                    roles: ROLE_INSTAGRAM
                user2:
                    # BCryptPasswordEncoder encripted password: 01010101
                    password: $2a$10$KSXr.ooY3qXA5/iQb2zH..9mfW5bpbJLII72Q7UfD.C7.kwCCKx3O
                    roles: ROLE_UBER
                user3:
                    # BCryptPasswordEncoder encripted password: $password
                    password: $2a$10$iDAUa8Ffo2KJqD0///YxHuxcJIOHK7jOz.L4EXwqDCkxzq.pwVibe
                    roles: ROLE_PETSTORE
                user4:
                    # BCryptPasswordEncoder encripted password: $my$password$
                    password: $2a$10$HDtpQ5sWOEpn6FQ4bigJmuvFg9UlsDTqeed8HnJzzp.4nACaoj.Jq
                    roles: ROLE_INSTAGRAM,ROLE_PETSTORE
